[terminal.shell]
program = "wsl.exe"
args = ["-d", "Ubuntu-24.04", "--cd", "~"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 12

[selection]
save_to_clipboard = true
